// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKBookClub.Models;

namespace SKBookClub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SKBookClub.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBookOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            GenreId = 1,
                            ImageThumbnailUrl = "https://i.ibb.co/VB0f6BM/Theshinning-small.jpg",
                            ImageUrl = "https://i.ibb.co/GMT7m40/theshinning.jpg",
                            InStock = true,
                            IsBookOfTheWeek = true,
                            LongDescription = "The Shining is a horror novel by American author Stephen King. Published in 1977. It is Kings third published novel and first hardback bestseller",
                            Price = 9.99m,
                            ShortDescription = "A Stephen King Horror Novel",
                            Title = "The Shining"
                        },
                        new
                        {
                            BookID = 2,
                            GenreId = 3,
                            ImageThumbnailUrl = "https://i.ibb.co/1Xfpnvx/Theinstitute-small.jpg",
                            ImageUrl = "https://i.ibb.co/ngj9Xgy/theinstitute.jpg",
                            InStock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "The Institute is a science fiction-horror thriller novel by American author Stephen King",
                            Price = 7.99m,
                            ShortDescription = "A Sci-Fi Thriller",
                            Title = "The Institute"
                        },
                        new
                        {
                            BookID = 3,
                            GenreId = 2,
                            ImageThumbnailUrl = "https://i.ibb.co/CBJDP2G/It-small.jpg",
                            ImageUrl = "https://i.ibb.co/NKVYZK4/it.jpg",
                            InStock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "It is a 1986 horror novel by American author Stephen King. The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself while hunting its prey",
                            Price = 7.99m,
                            ShortDescription = "Stephen King Bestselling Horror",
                            Title = "IT"
                        },
                        new
                        {
                            BookID = 4,
                            GenreId = 1,
                            ImageThumbnailUrl = "https://i.ibb.co/8NSKgr3/Petsematary-small.jpg",
                            ImageUrl = "https://i.ibb.co/F3Jyvbm/petsematary.jpg",
                            InStock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Pet Sematary is a 1983 horror novel by American writer Stephen King. The novel was nominated for a World Fantasy Award for Best Novel in 1986, and adapted into two films: one in 1989 and another in 2019",
                            Price = 4.99m,
                            ShortDescription = "A Stephen King Horror",
                            Title = "Pet Sematary"
                        },
                        new
                        {
                            BookID = 5,
                            GenreId = 1,
                            ImageThumbnailUrl = "https://i.ibb.co/GRkqJXk/ifitbleeds.jpg",
                            ImageUrl = "https://i.ibb.co/GRkqJXk/ifitbleeds.jpg",
                            InStock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "If It Bleeds is a 2020 collection of four previously unpublished novellas by American writer Stephen King. The stories in the collection are titled If It Bleeds Mr Harrigans Phone The Life of Chuck and Rat",
                            Price = 12.99m,
                            ShortDescription = "Latest from Stephen King",
                            Title = "If It Bleeds"
                        },
                        new
                        {
                            BookID = 6,
                            GenreId = 3,
                            ImageThumbnailUrl = "https://i.ibb.co/nn3WnSW/Finderskeepers-small.jpg",
                            ImageUrl = "https://i.ibb.co/3Yy2YnP/finderskeepers.jpg",
                            InStock = true,
                            IsBookOfTheWeek = false,
                            LongDescription = "Finders Keepers is a crime novel by American writer Stephen King published on June 2 2015. It is the second volume in a trilogy focusing on Detective Bill Hodges following Mr Mercedes",
                            Price = 4.99m,
                            ShortDescription = "Second in Bill Hodges Trilogy",
                            Title = "Finders Keepers"
                        });
                });

            modelBuilder.Entity("SKBookClub.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Supernatural"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Thriller"
                        });
                });

            modelBuilder.Entity("SKBookClub.Models.Book", b =>
                {
                    b.HasOne("SKBookClub.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
